---
title: "R Notebook"
output: html_notebook
author: ruonanjia
---
```{r}
# Download package tarball from CRAN archive

url <- "https://cran.r-project.org/src/contrib/Archive/zipcode/zipcode_1.0.tar.gz"
pkgFile <- "zipcode_1.0.tar.gz"
download.file(url = url, destfile = pkgFile)

# Install dependencies

install.packages(c("ada", "ipred", "evd"))

# Install package
install.packages(pkgs=pkgFile, type="source", repos=NULL)

# Delete package tarball
unlink(pkgFile)
```


load library
```{r}
library(ggplot2)
library(zipcode) # install only available through archive
library(maps)
library(ggpubr)
```

load data
```{r}
# setwd("E:/Ruonan/Projects in the lab/mdm_covid19/batch_data")
setwd("/Users/jiaruonan/Desktop/mdm_covid19/mdm_covid19_data")
load("data_all_444sub_rename.Rda")
load("data_all_444sub_rename_header.Rda")

```

take only the first response of the repeated subjects
```{r}
dupli <- data.all$WorkerId[duplicated(data.all$WorkerId)] 
dupli
length(dupli)

data.repeat <- data.all[is.element(data.all$WorkerId, dupli),]
nrow(data.repeat)
```


```{r}
colnames(data.all)
colnames(data.all)[c(155:164,166:171, 353)]
t(header[1, c(155:164,166:171, 353)])
```


demographic block
```{r}
data.demo <- data.all[,c(155:164,166:171, 353)]
View(data.demo)
colnames(data.demo)

data.demo$age <- as.numeric(as.character(data.demo$age)) + 17 # correct coding

# age
ggplot(data.demo, aes(x=age)) +
  geom_histogram(position = "identity", bins = 20) +
  labs(x = "Age")

# geo
data.demo$zip_postal_code <- as.numeric(as.character(data.demo$zip_postal_code))
data(zipcode)
data.demo$zipcode<- clean.zipcodes(data.demo$zip_postal_code)

#size by zip
data.zipcode<-aggregate(data.frame(count=data.demo$mTurkCode),list(zip=data.demo$zipcode),length)
geo<- merge(data.zipcode, zipcode, by='zip')

us<-map_data('state')

ggplot(geo,aes(longitude,latitude)) +
  geom_polygon(data=us,aes(x=long,y=lat,group=group),color='gray',fill=NA,alpha=.35) +
  geom_point(aes(color = count),size=0.8,alpha=0.4) + 
  # scale_colour_gradient(high="dark blue", low="light blue") +
  # scale_color_continuous(breaks = c(1,2), labels = c(1,2)) +
  theme(panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        panel.background = element_blank()) +
  xlim(-125,-65)+ylim(20,50)
  

```

ambiguity block
```{r}
colnames(data.all)
ambig_col <- c(172:220)
colnames(data.all)[ambig_col]
```

News source
```{r}
# rank news source
# ambig1_news_sources_1 - ambig1_news_sources_8_TEXT

# source of news influencing opinion
# ambig1_sourcebelief_1 - ambig1_sourcebelief_7_TEXT

# time consuming news perday
hist(as.numeric(as.character(data.all$ambig1_news_perday)))

```

Health impact vs. economics impact
```{r}
# data.all$ambig2_health_impact
# data.all$ambig2_economics
hist(as.numeric(as.character(data.all$ambig2_health_impact)),
     main = "Should consider health impact",
     xlab = "Extent")
hist(as.numeric(as.character(data.all$ambig2_economics)),
     main = "Should consider economics impact",
     xlab = "Extent")

ggplot(data.all, aes(x=ambig2_health_impact, y=ambig2_economics)) + 
  geom_bin2d() +
  xlab("health") + ylab("economics") + 
  ggtitle("2D histogram")
```

```{r}
# Q965 - Q1023
ambig_col <- c(193:198)

# Q975 how well informed you feel - Q985
for (i in 193:198) {
  data.all[, i] <- as.numeric(as.character(data.all[, i])) - 5
  data.all[data.all[,i]!=1, i] <- data.all[data.all[,i]!=1, i] - 6
}

data.all[,195]

library("PerformanceAnalytics")
my_data <- data.all[,193:198]
colnames(my_data) <- c("self", "government", "scientist", "healthcare", "economist", "familyfriends")

chart.Correlation(my_data, histogram=TRUE, pch=19)

data.all$Q975 <- as.numeric(as.character(data.all$Q975)) - 5
data.all$Q975[data.all$Q975!=1] <- data.all$Q975[data.all$Q975!=1] - 6 
```

risk exposure block
```{r}
data.all$Q1027
# those who themselves were infected with COVID-19
data.all$mTurkCode[data.all$Q1027 == 1]
# 2-immediate family, 3 - extended family, 9 - no
```

action block
```{r}

```


